CREATE TABLE "camp_years" (
	"year" integer NOT NULL,
	"camp_id" integer NOT NULL,
	"base_price" integer DEFAULT 0 NOT NULL,
	"capacity" integer,
	"start_date" date,
	"end_date" date,
	CONSTRAINT "camp_years_camp_id_year_pk" PRIMARY KEY("camp_id","year")
);
--> statement-breakpoint
CREATE TABLE "campers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" text NOT NULL,
	"name" text NOT NULL,
	"user_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "camps" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "camps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "registrations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "registrations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" text NOT NULL,
	"camp_id" integer NOT NULL,
	"camp_year" integer NOT NULL,
	"camper_id" integer,
	"is_paid" boolean DEFAULT false,
	CONSTRAINT "registrations_camper_id_camp_id_camp_year_unique" UNIQUE("camper_id","camp_id","camp_year")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_id" text NOT NULL,
	"email" text NOT NULL,
	"stripe_customer_id" text,
	CONSTRAINT "users_clerk_id_unique" UNIQUE("clerk_id")
);
--> statement-breakpoint
ALTER TABLE "camp_years" ADD CONSTRAINT "camp_years_camp_id_camps_id_fk" FOREIGN KEY ("camp_id") REFERENCES "public"."camps"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campers" ADD CONSTRAINT "campers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registrations" ADD CONSTRAINT "registrations_camper_id_campers_id_fk" FOREIGN KEY ("camper_id") REFERENCES "public"."campers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "registrations" ADD CONSTRAINT "registrations_camp_id_camp_year_camp_years_camp_id_year_fk" FOREIGN KEY ("camp_id","camp_year") REFERENCES "public"."camp_years"("camp_id","year") ON DELETE cascade ON UPDATE no action;