CREATE TABLE "addresses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "addresses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"address_line_1" text,
	"address_line_2" text,
	"city" text,
	"stateProv" text,
	"country" text,
	"postalZip" text
);
--> statement-breakpoint
CREATE TABLE "camper_addresses" (
	"camper_id" integer,
	"address_id" integer,
	CONSTRAINT "camper_addresses_camper_id_address_id_pk" PRIMARY KEY("camper_id","address_id")
);
--> statement-breakpoint
ALTER TABLE "campers" ADD COLUMN "swimming_level" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "campers" ADD COLUMN "gender" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "campers" ADD COLUMN "has_been_to_camp" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "campers" ADD COLUMN "shirt_size" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "camper_addresses" ADD CONSTRAINT "camper_addresses_camper_id_campers_id_fk" FOREIGN KEY ("camper_id") REFERENCES "public"."campers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "camper_addresses" ADD CONSTRAINT "camper_addresses_address_id_addresses_id_fk" FOREIGN KEY ("address_id") REFERENCES "public"."addresses"("id") ON DELETE no action ON UPDATE no action;